### ISSUE TITLE
plugin not loaded

### ISSUE THREAD

**Issue by WenFox** [MassiveCraft/Vampire#90]
Hi, the plugin is not loaded on the core of spigot version 1.7-1.8
Server log:

[Server thread/ERROR]: Error occurred while enabling Vampire v2.8.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/BannerMeta
	at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferMetaSpecific(ItemStackAdapterInnerV1_8.java:149) ~[?:?]
	at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferMeta(ItemStackAdapterInnerV1_7.java:227) ~[?:?]
	at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferAll(ItemStackAdapterInnerV1_7.java:140) ~[?:?]
	at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.erialize(ItemStackAdapterInnerV1_7.java:114) ~[?:?]
	at com.massivecraft.massivecore.adapter.ItemStackAdapter.deserialize(ItemStackAdapter.java:69) ~[?:?]
	at com.massivecraft.massivecore.adapter.ItemStackAdapter.deserialize(ItemStackAdapter.java:1) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:59) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:1) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:104) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:197) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:810) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:875) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:848) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:567) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:794) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.init(Coll.java:868) ~[?:?]
	at com.massivecraft.massivecore.store.Colls.getForCollname(Colls.java:81) ~[?:?]
	at com.massivecraft.massivecore.store.Colls.getForUniverse(Colls.java:71) ~[?:?]
	at com.massivecraft.massivecore.store.Colls.getColls(Colls.java:36) ~[?:?]
	at com.massivecraft.massivecore.store.Colls.init(Colls.java:26) ~[?:?]
	at com.massivecraft.vampire.Vampire.onEnable(Vampire.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.meta.BannerMeta
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	... 34 more

**Comment by ulumulu1510** [comment]
You were using a server version that pretended to be 1.8n thus our 1.8 features kicked in. Updating to a realy 1.8 build solves thia Problem.
